---
generic-service:
  nameOverride: hmpps-digital-prison-services
  serviceAccountName: hmpps-digital-prison-services
  productId: DPS019

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-digital-prison-services
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-digital-prison-services-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-digital-prison-services"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-digital-prison-services:
      CONTENTFUL_SPACE_ID: "CONTENTFUL_SPACE_ID"
      CONTENTFUL_ACCESS_TOKEN: "CONTENTFUL_ACCESS_TOKEN"
      TAG_MANAGER_CONTAINER_ID: "TAG_MANAGER_CONTAINER_ID"
    hmpps-digital-prison-services-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-digital-prison-services-auth-code:
      API_CLIENT_ID: "AUTH_CODE_CLIENT_ID"
      API_CLIENT_SECRET: "AUTH_CODE_CLIENT_SECRET"
    hmpps-digital-prison-services-client-creds:
      SYSTEM_CLIENT_ID: "CLIENT_CREDS_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "CLIENT_CREDS_CLIENT_SECRET"
    hmpps-digital-prison-services-session-secret:
      SESSION_SECRET: "SESSION_SECRET"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  targetApplication: hmpps-digital-prison-services

gotenberg:
  nameOverride: gotenberg
  replicaCount: 4

  image:
    repository: gotenberg/gotenberg
    tag: 8.17
    port: 3000

  containerCommand: [ "gotenberg" ]
  containerArgs:
    [
      "--chromium-ignore-certificate-errors",
      "--pdfengines-merge-engines=pdftk",
      "--libreoffice-disable-routes",
      "--webhook-disable",
      "--prometheus-disable-collect"
    ]

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    privileged: false
    runAsNonRoot: true
